### ISSUE TITLE
suggestions based on first try of template

### ISSUE THREAD

**Issue by paciorek** [berkeley-scf/stat999-myst#1]
Here's what I noticed:

- [x] The README indicates there is a `schedule.md`. We need to change that to indicate the schedule is on `index.md` and perhaps say something about the use of cards.
- [x] Is there a way to enable a search bar?
- [x] When we say "code cells are not yet actually executed", I'm confused. In Markdown, this is not yet available as MyST feature? And for ipynb, it does work now if one clicks on the execute cell icon, so can we clarify what we expect to work and what not?
- [ ] #2
    - [ ] Because we say to make a commit before running `myst init --gh-pages`, MyST tries a deployment that fails based on `deploy.yml`, so the user will get an email indicating that failure (e.g., [here's a failure from my test](https://github.com/paciorek/stat555-myst/actions/runs/6750145929)).
    - [ ] When one runs `myst init --gh-pages` it tells the user they need a new name for the deployment yml file, and then one would have two GH actions.
- [ ] I wonder if we should provide the details of what the user needs to do after `myst init --gh-pages`. 
    - [ ] MyST tells the user to "Enable GH pages" but it's not clear what to do to do that. I don't think the user needs to do anything specific for this.
    - [ ] MyST says to use GHA as the source. We may want to warn the user that it's ok that this is in Beta.

**Comment by ryanlovett** [comment]
Thanks!

- There's no search feature yet, https://mystmd.org/guide/seo-and-social.
- The `code-cell` directive did not work [as documented](https://mystmd.org/guide/code) for me. That is, I could not get myst to hand off the code-cell blocks to a jupyter kernel. I was able to itegrate .ipynb files without any trouble -- they are already executed.
- I hadn't considered the deploy issue. If we disable the deploy in this template, then there's nothing to demo at berkeley-scf-github.io/stat999-myst. Should we just remove the step to run `myst init --gh-pages`, or does that do something more than create the `deploy.yml` file?

**Comment by paciorek** [comment]
Yeah, I think we could remove the `myst init --gh-pages` step and tell the user at the step before making any commits to go to `https://github.com/example/stat555/settings/pages` and under **Build and deployment** select "GitHub Actions" as the *source*, noting it is listed as being in beta.

**Comment by paciorek** [comment]
I updated the text of the warning about non-run code in the `code-cell` directive to give more information.

**Comment by ryanlovett** [comment]
After some discussion, we realized that departmental staff will likely be the ones to fork the template or previous repo. This means that avoiding the initial action failure is not that big of a deal, although we do document it for ourselves.
